pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')  // Jenkins revisa cada 5 min si hay cambios
    }

    options {
        skipDefaultCheckout(false)
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'rama-mila',
                    url: 'https://github.com/ErickP25/PatrullApp.git'
            }
        }

        stage('Instalar dependencias') {
            steps {
                sh 'flutter pub get'
            }
        }

        stage('Analizar código') {
            steps {
                sh 'flutter analyze'
            }
        }

        stage('Ejecutar tests') {
            steps {
                sh 'flutter test || true'  
                // si no hay tests, no falla
            }
        }

        stage('Compilar debug') {
            steps {
                sh 'flutter build apk --debug'
            }
        }
    }
}
